name: Generate Powered-By
on:
  push:
    branches:
      - main

jobs:
  generate-powered-by:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        # Checkout code using massabot account
        token: ${{ secrets.MASSABOTCLASSIC }}

    - name: Install node 
      uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://registry.npmjs.org

    - name: Install license-report and jq
      run: |
        sudo apt-get update -y && sudo apt-get install -y jq
        sudo npm install -g license-report

    - name: Install project dependencies
      run: |
        npm ci

    - name: Generate Powered-By
      run: |
        ./generate_power-by.sh

    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        token: 
        commit_message: "Generate powered-by"
        file_pattern: "powered-by.md"
        # Commit code using massabot account that can bypass push and MR restriction
        commit_author: massabot <info@massa.net>
