name: Wallet example

on:
  [push]


jobs:
  run-wallet-example:
    defaults:
      run:
        working-directory: ./

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm install



      - name: Execute tests
        run: |
          if npm run test-wallet ; then
            echo "Successful execution!"
          else
            echo "Failed to execute contracts ..."
            exit 1
          fi
        env:
          JSON_RPC_URL_PUBLIC: https://buildnet.massa.net/api/v2
          JSON_RPC_URL_PRIVATE: https://buildnet.massa.net/api/v2
          DEPLOYER_PRIVATE_KEY: S1ykLaxXyMnJoaWLYds8UntqKTamZ4vcxrZ1fdToR8WpWEpk3FC
          RECEIVER_PRIVATE_KEY: S12srNEAvZrTb9pktYeuePpuM4taW5dfmWAZYtdqyETWTBspkoT1